### ISSUE TITLE
Error during compilation: This board is unknown. Make sure the chosen chip component is correct

### ISSUE THREAD

**Issue by GrumpyMeow** [limengdu/MR60BHA2_ESPHome_external_components#2]
I've just received a Seeed studio MR60BHA2. But using the given yaml file does not compile for me.
Is it maybe because of NixOS?

```
INFO ESPHome 2024.11.3
INFO Reading configuration /var/lib/private/esphome/slaapsensor.yaml...
INFO Updating https://github.com/limengdu/MR60BHA2_ESPHome_external_components@main
WARNING This board is unknown. Make sure the chosen chip component is correct.
ERROR Unable to import component seeed_mr60bha2.sensor:
Traceback (most recent call last):
  File "/nix/store/km26c21n9x4ml0yr1m86hgjf2xcqjhbm-esphome-2024.11.3/lib/python3.12/site-packages/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/lib/private/esphome/.esphome/external_components/60764085/components/seeed_mr60bha2/sensor.py", line 4, in <module>
    from esphome.const import (
ImportError: cannot import name 'ICON_HEART_PULSE' from 'esphome.const' (/nix/store/km26c21n9x4ml0yr1m86hgjf2xcqjhbm-esphome-2024.11.3/lib/python3.12/site-packages/esphome/const.py)
Failed config

sensor.seeed_mr60bha2: [source /var/lib/private/esphome/slaapsensor.yaml:98]
  
  Platform not found: 'sensor.seeed_mr60bha2'.
  platform: seeed_mr60bha2
  breath_rate: 
    name: Real-time respiratory rate
  heart_rate: 
    name: Real-time heart rate
  distance: 
    name: Distance to detection object
```

**Comment by GrumpyMeow** [comment]
It needs to be compiled with a very recent version of ESPHome: `2024.12.0-dev`
